name: check with gepetuto

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uv run gepetuto -vvca all

